spring:
  jpa:
    hibernate:
      ddl-auto: none

database:
  url: jdbc:h2:file:C:\Users\mariu\Documents\5_Semester\Projekt\webserver\spring\smartForrest\src\main\resources\default
  user: sa
  pw: sa

server:
  port: 8081
